variable "name" {
  description = "The name of the SAML provider."
  type        = string
}

variable "saml_metadata_document" {
  description = "An XML document generated by an identity provider that supports SAML 2.0. Required if saml_metadata_secret_id is not provided."
  type        = string
  default     = null
}

variable "saml_metadata_secret_id" {
  description = "The ID or ARN of the secret in Secrets Manager containing the SAML metadata document. If provided, this takes precedence over saml_metadata_document."
  type        = string
  default     = null
}

variable "saml_metadata_secret_key" {
  description = "The key in the Secrets Manager secret (JSON) that contains the SAML metadata document. If not provided, the entire secret string is used."
  type        = string
  default     = null
}

variable "tags" {
  description = "A map of tags to add to all resources."
  type        = map(string)
  default     = {}
}
